build:
  image: golang:1.5
  commands:
    - make deps
    - make vet
    - make build
    - make test

publish:
  docker:
    username: drone
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-opsworks
    when:
      branch: master

plugin:
  name: OpsWorks
  desc: Deploys or updates a project on OpsWorks
  type: deploy
  image: plugins/drone-opsworks
  labels:
    - aws
    - opsworks
